### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by hn18001** [wcq19941215/SceneTextRemoval#1]
Will you share the pretrained model?

**Comment by aiwolflow666** [comment]
Thank you for your attention, we will publish the pre-trained model and dataset soon




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "he ***@***.***&gt;; 
发送时间: 2021年5月21日(星期五) 上午8:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [wcq19941215/SceneTextRemoval] Pretrained Model (#1)





 
Will you share the pretrained model?

**Comment by hn18001** [comment]
Thanks.
