### ISSUE TITLE
Training path

### ISSUE THREAD

**Issue by UsamaRehman001** [wcq19941215/SceneTextRemoval#10]
Hi. Can you please tell about what's in the lists whose path you provided in config.yml. does that concated.txt contain only the images name or ground truth names, mask etc as well. Please assist so I can start training.

**Comment by aiwolflow666** [comment]
You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.

**Comment by UsamaRehman001** [comment]
> You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> 

My question to you is what's in the concat.txt only the train images names or their mask or gt as well.

**Comment by aiwolflow666** [comment]
> > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> 
> My question to you is what's in the concat.txt only the train images names or their mask or gt as well.

The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.

**Comment by UsamaRehman001** [comment]
> > > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> > 
> > My question to you is what's in the concat.txt only the train images names or their mask or gt as well.
> 
> The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.

Can you provide a sample concat.txt that will be of help. I have your dataset , I wanna do training on that, so I need to know the format of concat.txt. can you please provide that file , that will be of much much help.

**Comment by wcq19941215** [comment]
![image](https://user-images.githubusercontent.com/35086262/229437592-dc4973eb-1116-4f2a-a265-390ed34c8e92.png)

**Comment by aiwolflow666** [comment]
> > > > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> > > 
> > > 
> > > My question to you is what's in the concat.txt only the train images names or their mask or gt as well.
> > 
> > 
> > The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.
> 
> Can you provide a sample concat.txt that will be of help. I have your dataset , I wanna do training on that, so I need to know the format of concat.txt. can you please provide that file , that will be of much much help.

![image](https://user-images.githubusercontent.com/35086262/229437640-e6944282-9feb-4cc9-9d5a-7777af608084.png)

**Comment by UsamaRehman001** [comment]
> > > > > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> > > > 
> > > > 
> > > > My question to you is what's in the concat.txt only the train images names or their mask or gt as well.
> > > 
> > > 
> > > The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.
> > 
> > Can you provide a sample concat.txt that will be of help. I have your dataset , I wanna do training on that, so I need to know the format of concat.txt. can you please provide that file , that will be of much much help.
> 
> ![image](https://user-images.githubusercontent.com/35086262/229437640-e6944282-9feb-4cc9-9d5a-7777af608084.png)
> 

Kindly atleast show the image name and their parents folder so I could know, which is the path of image , which is the mask , and which is the gt.

**Comment by aiwolflow666** [comment]
> > > > > > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> > > > > 
> > > > > 
> > > > > My question to you is what's in the concat.txt only the train images names or their mask or gt as well.
> > > > 
> > > > 
> > > > The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.
> > > 
> > > 
> > > Can you provide a sample concat.txt that will be of help. I have your dataset , I wanna do training on that, so I need to know the format of concat.txt. can you please provide that file , that will be of much much help.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/35086262/229437640-e6944282-9feb-4cc9-9d5a-7777af608084.png)
> 
> Kindly atleast show the image name and their parents folder so I could know, which is the path of image , which is the mask , and which is the gt.

I should have said that there is only one image, which is gt, img, mask concat together.

**Comment by UsamaRehman001** [comment]
> > > > > > > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> > > > > > 
> > > > > > 
> > > > > > My question to you is what's in the concat.txt only the train images names or their mask or gt as well.
> > > > > 
> > > > > 
> > > > > The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.
> > > > 
> > > > 
> > > > Can you provide a sample concat.txt that will be of help. I have your dataset , I wanna do training on that, so I need to know the format of concat.txt. can you please provide that file , that will be of much much help.
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/35086262/229437640-e6944282-9feb-4cc9-9d5a-7777af608084.png)
> > 
> > Kindly atleast show the image name and their parents folder so I could know, which is the path of image , which is the mask , and which is the gt.
> 
> I should have said that there is only one image, which is gt, img, mask concat together.

We have to write our own code to concat them into one image, or you have done in done file ?

**Comment by aiwolflow666** [comment]
> > > > > > > > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> > > > > > > 
> > > > > > > 
> > > > > > > My question to you is what's in the concat.txt only the train images names or their mask or gt as well.
> > > > > > 
> > > > > > 
> > > > > > The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.
> > > > > 
> > > > > 
> > > > > Can you provide a sample concat.txt that will be of help. I have your dataset , I wanna do training on that, so I need to know the format of concat.txt. can you please provide that file , that will be of much much help.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/35086262/229437640-e6944282-9feb-4cc9-9d5a-7777af608084.png)
> > > 
> > > 
> > > Kindly atleast show the image name and their parents folder so I could know, which is the path of image , which is the mask , and which is the gt.
> > 
> > 
> > I should have said that there is only one image, which is gt, img, mask concat together.
> 
> We have to write our own code to concat them into one image, or you have done in done file ?

This is a very easy code operation, such as:
input = np.hstack((gt, img, mask))

**Comment by UsamaRehman001** [comment]
> > > > > > > > > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > My question to you is what's in the concat.txt only the train images names or their mask or gt as well.
> > > > > > > 
> > > > > > > 
> > > > > > > The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.
> > > > > > 
> > > > > > 
> > > > > > Can you provide a sample concat.txt that will be of help. I have your dataset , I wanna do training on that, so I need to know the format of concat.txt. can you please provide that file , that will be of much much help.
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/35086262/229437640-e6944282-9feb-4cc9-9d5a-7777af608084.png)
> > > > 
> > > > 
> > > > Kindly atleast show the image name and their parents folder so I could know, which is the path of image , which is the mask , and which is the gt.
> > > 
> > > 
> > > I should have said that there is only one image, which is gt, img, mask concat together.
> > 
> > We have to write our own code to concat them into one image, or you have done in done file ?
> 
> This is a very easy code operation, such as:
> input = np.hstack((gt, img, mask))

I got that , thanks for replying to my silly questions. 😊

**Comment by UsamaRehman001** [comment]
> > > You can find out how to load image data through concat.txt or concat.list in the data_load.py file. In model.py, you can see that gt, img, and mask are separated. Therefore, the data in concat.txt is combined into one image.
> > 
> > My question to you is what's in the concat.txt only the train images names or their mask or gt as well.
> 
> The concat.txt file contains only one verification set image. Each image contains gt, img, and mask.

Please also clarify for the validation list. @wcq19941215
