### ISSUE TITLE
Pretrained weights of other models

### ISSUE THREAD

**Issue by shannanyinxiang** [wcq19941215/SceneTextRemoval#11]
Could you please provide the pretrained weights of other models (e.g., EnsNet, EraseNet) using your Train_rw dataset?
Thank you!

**Comment by aiwolflow666** [comment]
You can retrain on ensnet and erasenet.

**Comment by shannanyinxiang** [comment]
OK.
Thanks!

**Comment by UsamaRehman001** [comment]
> Could you please provide the pretrained weights of other models (e.g., EnsNet, EraseNet) using your Train_rw dataset?
> Thank you!

Have you trained on Ensnet?

**Comment by shannanyinxiang** [comment]
> > Could you please provide the pretrained weights of other models (e.g., EnsNet, EraseNet) using your Train_rw dataset?
> > Thank you!
> 
> Have you trained on Ensnet?

Not yet.

**Comment by UsamaRehman001** [comment]
> > > Could you please provide the pretrained weights of other models (e.g., EnsNet, EraseNet) using your Train_rw dataset?
> > > Thank you!
> > 
> > Have you trained on Ensnet?
> 
> Not yet.

Ok I also seen there paper recently. Anyway I can contact with you. Maybe I need some guidance.

**Comment by UsamaRehman001** [comment]
> > > Could you please provide the pretrained weights of other models (e.g., EnsNet, EraseNet) using your Train_rw dataset?
> > > Thank you!
> > 
> > Have you trained on Ensnet?
> 
> Not yet.

On the other hand have you trained this repo model ?

**Comment by shannanyinxiang** [comment]
> > > > Could you please provide the pretrained weights of other models (e.g., EnsNet, EraseNet) using your Train_rw dataset?
> > > > Thank you!
> > > 
> > > 
> > > Have you trained on Ensnet?
> > 
> > 
> > Not yet.
> 
> On the other hand have you trained this repo model ?

I haven't trained this repo model.
I just ran the inference with the pretrained model.

**Comment by UsamaRehman001** [comment]
I am from outside the china, and cannot use the 'baidu' to download the pretrained model. can you share some other link for me.to download, if possible?

@shannanyinxiang

**Comment by UsamaRehman001** [comment]
> > > > > Could you please provide the pretrained weights of other models (e.g., EnsNet, EraseNet) using your Train_rw dataset?
> > > > > Thank you!
> > > > 
> > > > 
> > > > Have you trained on Ensnet?
> > > 
> > > 
> > > Not yet.
> > 
> > On the other hand have you trained this repo model ?
> 
> I haven't trained this repo model.
> I just ran the inference with the pretrained model.

Also I have a confusion about stacking the image and give as the path in config.yml. please confirm that's how to stack the image?
![Screenshot_20230409-161840.jpg](https://user-images.githubusercontent.com/66818827/230830477-a64d2ed0-fc50-47da-8275-cec9c200f4b5.jpg)

**Comment by shannanyinxiang** [comment]
> I am from outside the china, and cannot use the 'baidu' to download the pretrained model. can you share some other link for me.to download, if possible?
> 
> @shannanyinxiang

A Google Drive [link](https://drive.google.com/file/d/1t2tNFLemaSgPng5ubA2PFv_pZIRoMo2r/view?usp=sharing) of the pretrained model.

**Comment by UsamaRehman001** [comment]
> > I am from outside the china, and cannot use the 'baidu' to download the pretrained model. can you share some other link for me.to download, if possible?
> > 
> > @shannanyinxiang
> 
> A Google Drive [link](https://drive.google.com/file/d/1t2tNFLemaSgPng5ubA2PFv_pZIRoMo2r/view?usp=sharing) of the pretrained model.

This is the link for EnsNet?

**Comment by shannanyinxiang** [comment]
> > > I am from outside the china, and cannot use the 'baidu' to download the pretrained model. can you share some other link for me.to download, if possible?
> > > @shannanyinxiang
> > 
> > 
> > A Google Drive [link](https://drive.google.com/file/d/1t2tNFLemaSgPng5ubA2PFv_pZIRoMo2r/view?usp=sharing) of the pretrained model.
> 
> This is the link for EnsNet?

It is the pretrained model of this repo.

**Comment by UsamaRehman001** [comment]
> > > > I am from outside the china, and cannot use the 'baidu' to download the pretrained model. can you share some other link for me.to download, if possible?
> > > > @shannanyinxiang
> > > 
> > > 
> > > A Google Drive [link](https://drive.google.com/file/d/1t2tNFLemaSgPng5ubA2PFv_pZIRoMo2r/view?usp=sharing) of the pretrained model.
> > 
> > This is the link for EnsNet?
> 
> It is the pretrained model of this repo.

Thanks @shannanyinxiang 

Can I ask a little bit infor like in config.yml I concatenated the Train_rw and given it's path in the training list..what images or path should I give in the validation list please guide

**Comment by shannanyinxiang** [comment]
> > > > > I am from outside the china, and cannot use the 'baidu' to download the pretrained model. can you share some other link for me.to download, if possible?
> > > > > @shannanyinxiang
> > > > 
> > > > 
> > > > A Google Drive [link](https://drive.google.com/file/d/1t2tNFLemaSgPng5ubA2PFv_pZIRoMo2r/view?usp=sharing) of the pretrained model.
> > > 
> > > 
> > > This is the link for EnsNet?
> > 
> > 
> > It is the pretrained model of this repo.
> 
> Thanks @shannanyinxiang
> 
> Can I ask a little bit infor like in config.yml I concatenated the Train_rw and given it's path in the training list..what images or path should I give in the validation list please guide

I just ran the testing that does not require a `config.yml`, so I can not answer your question at this time.

**Comment by UsamaRehman001** [comment]
> > > > > > I am from outside the china, and cannot use the 'baidu' to download the pretrained model. can you share some other link for me.to download, if possible?
> > > > > > @shannanyinxiang
> > > > > 
> > > > > 
> > > > > A Google Drive [link](https://drive.google.com/file/d/1t2tNFLemaSgPng5ubA2PFv_pZIRoMo2r/view?usp=sharing) of the pretrained model.
> > > > 
> > > > 
> > > > This is the link for EnsNet?
> > > 
> > > 
> > > It is the pretrained model of this repo.
> > 
> > 
> > Thanks @shannanyinxiang
> > Can I ask a little bit infor like in config.yml I concatenated the Train_rw and given it's path in the training list..what images or path should I give in the validation list please guide
> 
> I just ran the testing that does not require a `config.yml`, so I can not answer your question at this time.

any update?
