### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by UsamaRehman001** [wcq19941215/SceneTextRemoval#12]
Test_ox or Test_rw which one to take for validation.txt?

**Comment by UsamaRehman001** [comment]
@weizequan

**Comment by UsamaRehman001** [comment]
> Test_ox or Test_rw which one to take for validation.txt?

I am only asking because the dataset  which you gave access, contain only 3 folders , train_rw, test_rw, test_ox. I will be needing the train_ox.

@wcq19941215 @weizequan

**Comment by aiwolflow666** [comment]
#13

**Comment by UsamaRehman001** [comment]
> #13 

That think is for training list. I am asking about validation. Which images path are in the validation? How did you made a validation list. Please assist

**Comment by UsamaRehman001** [comment]
> > #13 
> 
> That think is for training list. I am asking about validation. Which images path are in the validation? How did you made a validation list. Please assist

@wcq19941215
