### ISSUE TITLE
Stacked images 

### ISSUE THREAD

**Issue by UsamaRehman001** [wcq19941215/SceneTextRemoval#13]
Is this the correctly stacked images to give path to in config.ywl

![Screenshot_20230409-161840.jpg](https://user-images.githubusercontent.com/66818827/230769453-ac0a9c94-2930-44d7-97ca-8cd4478f88fc.jpg)

**Comment by aiwolflow666** [comment]
From your question, I think you need to read the code and the paper more carefully, all the details are in the code, and you are free to modify the data processing.

**Comment by UsamaRehman001** [comment]
I have, I am just confirming You asked me stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm

**Comment by UsamaRehman001** [comment]
> @wcq19941215 
I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm

**Comment by wcq19941215** [comment]
The model.py file contains the following code:
def textremoval_model(self, batch_data, training=True,reuse=False):
        batch_batch = batch_data
        batch_width = int(batch_batch.get_shape().as_list()[2]/5)
        batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
        batch_img = batch_batch[:, :, batch_width:batch_width*2,:] / 127.5 - 1. # raw image with text
        batch_mask = tf.cast(batch_batch[:, :, batch_width*2:batch_width*3,0:1] > 127.5, tf.float32) # text region mask
        batch_text = tf.cast(batch_batch[:, :, batch_width*3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask

After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.

**Comment by aiwolflow666** [comment]
> > @wcq19941215
> > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm

The model.py file contains the following code:
```
def textremoval_model(self, batch_data, training=True,reuse=False):
  batch_batch = batch_data
  batch_width = int(batch_batch.get_shape().as_list()[2]/5)
  batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
  batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
  batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
  batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
```
After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.

**Comment by UsamaRehman001** [comment]
> > > @wcq19941215
> > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> 
> The model.py file contains the following code:
> ```
> def textremoval_model(self, batch_data, training=True,reuse=False):
>   batch_batch = batch_data
>   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
>   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
>   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
>   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
>   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> ```
> After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.

I guess we have confusion here.

I know well that data will be splitted.
My question did I stacked images correctly as shown in above picture " I stacked the image, it's gt and it's mask in a horizontal manner" so I am confirming that , my stacked images in well suited for model or do I need to stack it with respect to channels?

**Comment by UsamaRehman001** [comment]
> > > @wcq19941215
> > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> 
> The model.py file contains the following code:
> ```
> def textremoval_model(self, batch_data, training=True,reuse=False):
>   batch_batch = batch_data
>   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
>   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
>   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
>   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
>   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> ```
> After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.

Also confirm me that we only have to concat the 'image , mask and gt' right ? Or do I also need to stack the text. Kindly confirm in which order do I stack them.

**Comment by aiwolflow666** [comment]
> > > > @wcq19941215
> > > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> > 
> > 
> > The model.py file contains the following code:
> > ```
> > def textremoval_model(self, batch_data, training=True,reuse=False):
> >   batch_batch = batch_data
> >   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
> >   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
> >   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
> >   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
> >   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.
> 
> Also confirm me that we only have to concat the 'image , mask and gt' right ? Or do I also need to stack the text. Kindly confirm in which order do I stack them.

I think the code is very clear. Please read it carefully and understand the meaning of the code.

**Comment by UsamaRehman001** [comment]
> > > > > @wcq19941215
> > > > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> > > 
> > > 
> > > The model.py file contains the following code:
> > > ```
> > > def textremoval_model(self, batch_data, training=True,reuse=False):
> > >   batch_batch = batch_data
> > >   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
> > >   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
> > >   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
> > >   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
> > >   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.
> > 
> > Also confirm me that we only have to concat the 'image , mask and gt' right ? Or do I also need to stack the text. Kindly confirm in which order do I stack them.
> 
> I think the code is very clear. Please read it carefully and understand the meaning of the code.

Sir with due respect I am just clearing the things, because last time I asked you only said to stack the image, gt and mask. That's why I am kind of confused.

Can you atleast confirm that I have to stack the images horizontally like using (np.hstack()).
Also please tell me how can I get the train_ox. I wrote the email, got the responce back, but that has only 3 folders 'train_rw, test_rw, test_ox'

**Comment by aiwolflow666** [comment]
> > > > > > @wcq19941215
> > > > > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> > > > 
> > > > 
> > > > The model.py file contains the following code:
> > > > ```
> > > > def textremoval_model(self, batch_data, training=True,reuse=False):
> > > >   batch_batch = batch_data
> > > >   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
> > > >   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
> > > >   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
> > > >   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
> > > >   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.
> > > 
> > > 
> > > Also confirm me that we only have to concat the 'image , mask and gt' right ? Or do I also need to stack the text. Kindly confirm in which order do I stack them.
> > 
> > 
> > I think the code is very clear. Please read it carefully and understand the meaning of the code.
> 
> Sir with due respect I am just clearing the things, because last time I asked you only said to stack the image, gt and mask. That's why I am kind of confused.
> 
> Can you atleast confirm that I have to stack the images horizontally like using (np.hstack()). Also please tell me how can I get the train_ox. I wrote the email, got the responce back, but that has only 3 folders 'train_rw, test_rw, test_ox'

The train_ox dataset is explained in the paper, because this is not our public dataset, you can find the dataset at https://github.com/ankush-me/SynthText

**Comment by aiwolflow666** [comment]
> > > > > > > @wcq19941215
> > > > > > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> > > > > 
> > > > > 
> > > > > The model.py file contains the following code:
> > > > > ```
> > > > > def textremoval_model(self, batch_data, training=True,reuse=False):
> > > > >   batch_batch = batch_data
> > > > >   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
> > > > >   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
> > > > >   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
> > > > >   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
> > > > >   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.
> > > > 
> > > > 
> > > > Also confirm me that we only have to concat the 'image , mask and gt' right ? Or do I also need to stack the text. Kindly confirm in which order do I stack them.
> > > 
> > > 
> > > I think the code is very clear. Please read it carefully and understand the meaning of the code.
> > 
> > 
> > Sir with due respect I am just clearing the things, because last time I asked you only said to stack the image, gt and mask. That's why I am kind of confused.
> > Can you atleast confirm that I have to stack the images horizontally like using (np.hstack()). Also please tell me how can I get the train_ox. I wrote the email, got the responce back, but that has only 3 folders 'train_rw, test_rw, test_ox'
> 
> The train_ox dataset is explained in the paper, because this is not our public dataset, you can find the dataset at https://github.com/ankush-me/SynthText

The concat example you gave is right, but the text stroke mask is missing.

**Comment by UsamaRehman001** [comment]
> > > > > > > > @wcq19941215
> > > > > > > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> > > > > > 
> > > > > > 
> > > > > > The model.py file contains the following code:
> > > > > > ```
> > > > > > def textremoval_model(self, batch_data, training=True,reuse=False):
> > > > > >   batch_batch = batch_data
> > > > > >   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
> > > > > >   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
> > > > > >   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
> > > > > >   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
> > > > > >   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.
> > > > > 
> > > > > 
> > > > > Also confirm me that we only have to concat the 'image , mask and gt' right ? Or do I also need to stack the text. Kindly confirm in which order do I stack them.
> > > > 
> > > > 
> > > > I think the code is very clear. Please read it carefully and understand the meaning of the code.
> > > 
> > > 
> > > Sir with due respect I am just clearing the things, because last time I asked you only said to stack the image, gt and mask. That's why I am kind of confused.
> > > Can you atleast confirm that I have to stack the images horizontally like using (np.hstack()). Also please tell me how can I get the train_ox. I wrote the email, got the responce back, but that has only 3 folders 'train_rw, test_rw, test_ox'
> > 
> > The train_ox dataset is explained in the paper, because this is not our public dataset, you can find the dataset at https://github.com/ankush-me/SynthText
> 
> The concat example you gave is right, but the text stroke mask is missing.

Thanks that's all I wanted to clear.

**Comment by aiwolflow666** [comment]
> > > > > > > > > @wcq19941215
> > > > > > > > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> > > > > > > 
> > > > > > > 
> > > > > > > The model.py file contains the following code:
> > > > > > > ```
> > > > > > > def textremoval_model(self, batch_data, training=True,reuse=False):
> > > > > > >   batch_batch = batch_data
> > > > > > >   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
> > > > > > >   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
> > > > > > >   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
> > > > > > >   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
> > > > > > >   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.
> > > > > > 
> > > > > > 
> > > > > > Also confirm me that we only have to concat the 'image , mask and gt' right ? Or do I also need to stack the text. Kindly confirm in which order do I stack them.
> > > > > 
> > > > > 
> > > > > I think the code is very clear. Please read it carefully and understand the meaning of the code.
> > > > 
> > > > 
> > > > Sir with due respect I am just clearing the things, because last time I asked you only said to stack the image, gt and mask. That's why I am kind of confused.
> > > > Can you atleast confirm that I have to stack the images horizontally like using (np.hstack()). Also please tell me how can I get the train_ox. I wrote the email, got the responce back, but that has only 3 folders 'train_rw, test_rw, test_ox'
> > > 
> > > 
> > > The train_ox dataset is explained in the paper, because this is not our public dataset, you can find the dataset at https://github.com/ankush-me/SynthText
> > 
> > 
> > The concat example you gave is right, but the text stroke mask is missing.
> 
> Thanks that's all I wanted to clear.

You're welcome. I hope it's helpful to your work.

**Comment by UsamaRehman001** [comment]
> > > > > > > > > > @wcq19941215
> > > > > > > > > > I have, I am just confirming You asked me to stack the images using 'hstack' and then store those images path in txt file. So I am confirming is this the stacked images to give as Input, because you mentioned it will be separated during training. That's what I am confirming that this is the kind of image to give as Input. Kindly confirm
> > > > > > > > 
> > > > > > > > 
> > > > > > > > The model.py file contains the following code:
> > > > > > > > ```
> > > > > > > > def textremoval_model(self, batch_data, training=True,reuse=False):
> > > > > > > >   batch_batch = batch_data
> > > > > > > >   batch_width = int(batch_batch.get_shape().as_list()[2]/5)
> > > > > > > >   batch_gt = batch_batch[:, :, :batch_width,:] / 127.5 - 1.
> > > > > > > >   batch_img = batch_batch[:, :, batch_width:batch_width2,:] / 127.5 - 1. # raw image with text
> > > > > > > >   batch_mask = tf.cast(batch_batch[:, :, batch_width2:batch_width3,0:1] > 127.5, tf.float32) # text region mask
> > > > > > > >   batch_text = tf.cast(batch_batch[:, :, batch_width3:batch_width*4,0:1] > 127.5, tf.float32) # text stroke mask
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > >     
> > > > > > > >       
> > > > > > > >     
> > > > > > > > 
> > > > > > > >       
> > > > > > > >     
> > > > > > > > 
> > > > > > > >     
> > > > > > > >   
> > > > > > > > After batch_data is loaded, the code is split into batch_gt, batch-img, batch_mask, and batch_text.
> > > > > > > 
> > > > > > > 
> > > > > > > Also confirm me that we only have to concat the 'image , mask and gt' right ? Or do I also need to stack the text. Kindly confirm in which order do I stack them.
> > > > > > 
> > > > > > 
> > > > > > I think the code is very clear. Please read it carefully and understand the meaning of the code.
> > > > > 
> > > > > 
> > > > > Sir with due respect I am just clearing the things, because last time I asked you only said to stack the image, gt and mask. That's why I am kind of confused.
> > > > > Can you atleast confirm that I have to stack the images horizontally like using (np.hstack()). Also please tell me how can I get the train_ox. I wrote the email, got the responce back, but that has only 3 folders 'train_rw, test_rw, test_ox'
> > > > 
> > > > 
> > > > The train_ox dataset is explained in the paper, because this is not our public dataset, you can find the dataset at https://github.com/ankush-me/SynthText
> > > 
> > > 
> > > The concat example you gave is right, but the text stroke mask is missing.
> > 
> > Thanks that's all I wanted to clear.
> 
> You're welcome. I hope it's helpful to your work.

@wcq19941215  can you guys provide the code for generating the binary mask and text mask. ?
