### ISSUE TITLE
how to create concatenated images?

### ISSUE THREAD

**Issue by KangBK0120** [wcq19941215/SceneTextRemoval#2]
Hi, 

Thanks for sharing the work.

It is written that gt, mask, and images are concatenated into a single image. 
Then you specify the list file in the config file when you train the model. However, I don't know how it looks like.
Do you have any script(or code) for concatenating data and creating a list file? Thanks.

**Comment by aiwolflow666** [comment]
Thank you for your attention to our work^-^
For example, if there are three images of gt mask and image, and their height and width are 256, then the three concats together will be a single image with a height of 256 and a width of 768, which is easy to implement with opencv:
 
```
import cv2
image = cv2.imread(image_file)
mask = cv2.imread(mask_file)
gt = cv2.imread(gt_file)
text_mask = cv2.imread(text_mask_file)
res = cv2.hconcat([gt, image, mask,text_mask])
cv2.imwrite(img_saving_path, res)
```

**Comment by KangBK0120** [comment]
Thanks for the reply!

Then what is the format of `TRAIN_CONCAT_FLIST` and `VAL_CONCAT_FLIST`? Concatenated images name per line?

**Comment by aiwolflow666** [comment]
yes!



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 28, 2021 22:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wcq19941215/SceneTextRemoval] how to create concatenated images? (#2)




 
Thanks for the reply!
 
Then what is the format of TRAIN_CONCAT_FLIST and VAL_CONCAT_FLIST? Concatenated images name per line?
