### ISSUE TITLE
Resizing images

### ISSUE THREAD

**Issue by quincylin1** [wcq19941215/SceneTextRemoval#5]
Hi,
I am wondering how you resize your real world oxford dataset to 256 x 256? Would appreciate if you could provide some details, thanks :)

**Comment by aiwolflow666** [comment]
Thank you for your interest in our work.
Here's how we use the oxford dataset,
1. Resize the oxford image without text to the desired size.
2. SynthText is used for synthesis,
3. Select images whose text composition is more natural and whose text coverage area is greater than 20% as the data set.
4. The image with text and the image without text are subtracted according to the absolute value, and the binarized mask is obtained through the empirical threshold.
5. we get the synthesized text image, gt, mask
