### ISSUE TITLE
Training dataset format

### ISSUE THREAD

**Issue by JIaqiYang78** [wcq19941215/SceneTextRemoval#7]
Hi, can you add a readme about the training dataset? For example, except images, does the text region mask is in a txt file which saved the bounding box of the text? And whether there are only images and txt fiels for data set?

**Comment by aiwolflow666** [comment]
The region mask and stroke mask are binarized images,
stroke mask: The white area indicates the text stroke area, and the black area indicates the non-text stroke area.
region mask: The white area indicates the rectangle bounding box area of text, and the black area indicates the non-text area.

**Comment by Apostatee** [comment]
Where can I download your training dataset ?

**Comment by Apostatee** [comment]
> Where can I download your training dataset ?



> The region mask and stroke mask are binarized images, stroke mask: The white area indicates the text stroke area, and the black area indicates the non-text stroke area. region mask: The white area indicates the rectangle bounding box area of text, and the black area indicates the non-text area.

Where can I download your training dataset ?

**Comment by UsamaRehman001** [comment]
> Hi, can you add a readme about the training dataset? For example, except images, does the text region mask is in a txt file which saved the bounding box of the text? And whether there are only images and txt fiels for data set? 

Have you figured out the text files format ??? Please assist

**Comment by aiwolflow666** [comment]
> > Where can I download your training dataset ?
> 
> > The region mask and stroke mask are binarized images, stroke mask: The white area indicates the text stroke area, and the black area indicates the non-text stroke area. region mask: The white area indicates the rectangle bounding box area of text, and the black area indicates the non-text area.
> 
> Where can I download your training dataset ?

The dataset can be obtained by sending a request email to us. Specifically, the researchers should download and fill up this [Agreement Form](https://github.com/wcq19941215/SceneTextRemoval/blob/main/Agreement_form.doc) and send it back to Weize Quan (weize.quan AT nlpr.ia.ac.cn; Email title: Scene Text Removal Dataset Request). We will then send you the download instructions at our discretion.

**Comment by aiwolflow666** [comment]
> > Hi, can you add a readme about the training dataset? For example, except images, does the text region mask is in a txt file which saved the bounding box of the text? And whether there are only images and txt fiels for data set?
> 
> Have you figured out the text files format ??? Please assist

#10
