### ISSUE TITLE
Is your real text removal dataset open?

### ISSUE THREAD

**Issue by DerekRay** [wcq19941215/SceneTextRemoval#9]

**Comment by aiwolflow666** [comment]
The dataset can be obtained by sending a request email to us. Specifically, the researchers should download and fill up this [Agreement Form](https://github.com/wcq19941215/SceneTextRemoval/blob/main/Agreement_form.doc) and send it back to Weize Quan (weize.quan AT nlpr.ia.ac.cn; Email title: Scene Text Removal Dataset Request). We will then send you the download instructions at our discretion.
